spring:
  config:
    import: optional:configserver:http://config-server:8763

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://naming-server:8761/eureka
